
=====================================================================
This module is intended solely for building or source activating user
python environments, i.e.,

    mamba create -n myenv -c conda-forge

or

    source activate myenv

To list available environments, run:

    mamba info --envs

See our docs: https://links.asu.edu/solpy

Any other use is NOT TESTED.
=====================================================================

  
/scratch/zzhou82/2024_0308/DiffTumor/STEP1.AutoencoderModel/vq_gan_3d/model/lpips.py:82: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if name is not "vgg_lpips":
train len 5195
Loading dataset:   0%|          | 0/259 [00:00<?, ?it/s]Loading dataset:   0%|          | 0/259 [00:00<?, ?it/s]BDMAP_00000001
BDMAP_00000002
BDMAP_00000003
BDMAP_00000004
BDMAP_00000005
BDMAP_00000006
BDMAP_00000007
BDMAP_00000008
BDMAP_00000009
BDMAP_00000010
BDMAP_00000011
BDMAP_00000012
BDMAP_00000013
BDMAP_00000014
BDMAP_00000015
BDMAP_00000016
BDMAP_00000017
BDMAP_00000018
BDMAP_00000019
BDMAP_00000020
BDMAP_00000021
BDMAP_00000022
BDMAP_00000023
BDMAP_00000024
BDMAP_00000025
BDMAP_00000026
BDMAP_00000027
BDMAP_00000028
BDMAP_00000029
BDMAP_00000030
BDMAP_00000031
BDMAP_00000032
BDMAP_00000033
BDMAP_00000034
BDMAP_00000035
BDMAP_00000036
BDMAP_00000037
BDMAP_00000038
BDMAP_00000039
BDMAP_00000040
BDMAP_00000041
BDMAP_00000042
BDMAP_00000043
BDMAP_00000044
BDMAP_00000045
BDMAP_00000046
BDMAP_00000047
BDMAP_00000048
BDMAP_00000049
BDMAP_00000050
BDMAP_00000051
BDMAP_00000052
BDMAP_00000053
BDMAP_00000054
BDMAP_00000055
BDMAP_00000056
BDMAP_00000057
BDMAP_00000058
BDMAP_00000059
BDMAP_00000060
BDMAP_00000061
BDMAP_00000062
BDMAP_00000063
BDMAP_00000064
BDMAP_00000065
BDMAP_00000066
BDMAP_00000067
BDMAP_00000068
BDMAP_00000069
BDMAP_00000070
BDMAP_00000071
BDMAP_00000072
BDMAP_00000073
BDMAP_00000074
BDMAP_00000075
BDMAP_00000076
BDMAP_00000077
BDMAP_00000078
BDMAP_00000079
BDMAP_00000080
BDMAP_00000081
BDMAP_00000082
BDMAP_00000083

Error executing job with overrides: ['dataset.data_root_path=/scratch/zzhou82/data/AbdomenAtlas1.0Mini/', 'dataset.dataset_list=AbdomenAtlasMini1.0', 'dataset.cache_rate=0.05', 'dataset.batch_size=8', 'model.gpus=1']
Traceback (most recent call last):
  File "/home/zzhou82/.conda/envs/difftumor/lib/python3.8/site-packages/monai/transforms/transform.py", line 89, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/home/zzhou82/.conda/envs/difftumor/lib/python3.8/site-packages/monai/transforms/transform.py", line 53, in _apply_transform
    return transform(parameters)
  File "/scratch/zzhou82/2024_0308/DiffTumor/STEP1.AutoencoderModel/dataset/dataloader.py", line 152, in __call__
    raise ValueError("loader must return a tuple or list (because image_only=False was used).")
ValueError: loader must return a tuple or list (because image_only=False was used).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 27, in run
    train_dataloader, train_sampler, dataset_size = get_loader(cfg.dataset)
  File "/scratch/zzhou82/2024_0308/DiffTumor/STEP1.AutoencoderModel/dataset/dataloader.py", line 333, in get_loader
    train_dataset = CacheDataset(data=data_dicts_train, transform=train_transforms, cache_rate=args.cache_rate)
  File "/home/zzhou82/.conda/envs/difftumor/lib/python3.8/site-packages/monai/data/dataset.py", line 723, in __init__
    self.set_data(data)
  File "/home/zzhou82/.conda/envs/difftumor/lib/python3.8/site-packages/monai/data/dataset.py", line 748, in set_data
    self._cache = _compute_cache()
  File "/home/zzhou82/.conda/envs/difftumor/lib/python3.8/site-packages/monai/data/dataset.py", line 737, in _compute_cache
    return self._fill_cache()
  File "/home/zzhou82/.conda/envs/difftumor/lib/python3.8/site-packages/monai/data/dataset.py", line 757, in _fill_cache
    return list(
  File "/home/zzhou82/.conda/envs/difftumor/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/zzhou82/.conda/envs/difftumor/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/home/zzhou82/.conda/envs/difftumor/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/zzhou82/.conda/envs/difftumor/lib/python3.8/site-packages/monai/data/dataset.py", line 777, in _load_cache_item
    item = apply_transform(_xform, item)
  File "/home/zzhou82/.conda/envs/difftumor/lib/python3.8/site-packages/monai/transforms/transform.py", line 113, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <dataset.dataloader.LoadImaged_BodyMap object at 0x155493272160>

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
